back-animation:
  type: 2
  path: [
    "/images/back-animation/1.png",
    "/images/back-animation/2.png",
    "/images/back-animation/3.png",
    "/images/back-animation/4.png",
    "/images/back-animation/5.png",
    "/images/back-animation/6.png",
    "/images/back-animation/7.png",
    "/images/back-animation/8.png",
    "/images/back-animation/9.png",
    "/images/back-animation/10.png",
    "/images/back-animation/11.png",
    "/images/back-animation/12.png",
    "/images/back-animation/13.png",
    "/images/back-animation/14.png"
  ]
  description: "Animation vers le haut"
  rotation: 1
death-animation:
  type: 2
  path: [
    "/images/death-animation/1.png",
    "/images/death-animation/2.png",
    "/images/death-animation/3.png",
    "/images/death-animation/4.png",
    "/images/death-animation/5.png",
    "/images/death-animation/6.png",
    "/images/death-animation/7.png"
  ]
  description: "Mort"
  rotation: 1
front-animation:
  type: 2
  path: [
    "/images/front-animation/1.png",
    "/images/front-animation/2.png",
    "/images/front-animation/3.png",
    "/images/front-animation/4.png",
    "/images/front-animation/5.png",
    "/images/front-animation/6.png",
    "/images/front-animation/7.png",
    "/images/front-animation/8.png",
    "/images/front-animation/9.png",
    "/images/front-animation/10.png",
    "/images/front-animation/11.png",
    "/images/front-animation/12.png",
    "/images/front-animation/13.png",
    "/images/front-animation/14.png"
  ]
  description: "Animation vers le bas"
  rotation: 1
left-animation:
  type: 2
  path: [
    "/images/left-animation/1.png",
    "/images/left-animation/2.png",
    "/images/left-animation/3.png",
    "/images/left-animation/4.png",
    "/images/left-animation/5.png",
    "/images/left-animation/6.png",
    "/images/left-animation/7.png",
    "/images/left-animation/8.png",
    "/images/left-animation/9.png",
    "/images/left-animation/10.png",
    "/images/left-animation/11.png",
    "/images/left-animation/12.png",
    "/images/left-animation/13.png",
    "/images/left-animation/14.png"
  ]
  description: "Animation vers la gauche"
  rotation: 1
right-animation:
  type: 2
  path: [
    "/images/right-animation/1.png",
    "/images/right-animation/2.png",
    "/images/right-animation/3.png",
    "/images/right-animation/4.png",
    "/images/right-animation/5.png",
    "/images/right-animation/6.png",
    "/images/right-animation/7.png",
    "/images/right-animation/8.png",
    "/images/right-animation/9.png",
    "/images/right-animation/10.png",
    "/images/right-animation/11.png",
    "/images/right-animation/12.png",
    "/images/right-animation/13.png",
    "/images/right-animation/14.png"
  ]
  description: "Animation vers la droite"
  rotation: 1
victory-animation:
  type: 2
  path: [
    "/images/victory-animation/1.png",
    "/images/victory-animation/2.png",
    "/images/victory-animation/3.png",
    "/images/victory-animation/4.png",
    "/images/victory-animation/5.png",
    "/images/victory-animation/6.png",
    "/images/victory-animation/7.png",
    "/images/victory-animation/8.png",
    "/images/victory-animation/9.png",
    "/images/victory-animation/10.png",
    "/images/victory-animation/11.png",
    "/images/victory-animation/12.png",
    "/images/victory-animation/13.png",
    "/images/victory-animation/14.png",
    "/images/victory-animation/15.png",
    "/images/victory-animation/16.png",
    "/images/victory-animation/17.png"
  ]
  description: "Animation de victoire"
  rotation: 1
idle-front-animation:
  type: 2
  path: [
    "/images/idle-front-animation/1.png",
    "/images/idle-front-animation/2.png",
    "/images/idle-front-animation/3.png",
    "/images/idle-front-animation/4.png",
    "/images/idle-front-animation/5.png",
    "/images/idle-front-animation/6.png",
    "/images/idle-front-animation/7.png",
    "/images/idle-front-animation/8.png",
    "/images/idle-front-animation/9.png",
    "/images/idle-front-animation/10.png",
    "/images/idle-front-animation/11.png",
    "/images/idle-front-animation/12.png",
    "/images/idle-front-animation/13.png",
    "/images/idle-front-animation/14.png",
    "/images/idle-front-animation/15.png",
    "/images/idle-front-animation/16.png",
    "/images/idle-front-animation/17.png"
  ]
  description: "Animation de position statique de face"
  rotation: 1
idle-back-animation:
  type: 2
  path: [
    "/images/idle-back-animation/1.png",
    "/images/idle-back-animation/2.png",
    "/images/idle-back-animation/3.png",
    "/images/idle-back-animation/4.png",
    "/images/idle-back-animation/5.png",
    "/images/idle-back-animation/6.png",
    "/images/idle-back-animation/7.png",
    "/images/idle-back-animation/8.png",
    "/images/idle-back-animation/9.png",
    "/images/idle-back-animation/10.png",
    "/images/idle-back-animation/11.png",
    "/images/idle-back-animation/12.png",
    "/images/idle-back-animation/13.png",
    "/images/idle-back-animation/14.png",
    "/images/idle-back-animation/15.png",
    "/images/idle-back-animation/16.png",
    "/images/idle-back-animation/17.png"
  ]
  description: "Animation de position statique de dos"
  rotation: 1
idle-left-animation:
  type: 2
  path: [
    "/images/idle-left-animation/1.png",
    "/images/idle-left-animation/2.png",
    "/images/idle-left-animation/3.png",
    "/images/idle-left-animation/4.png",
    "/images/idle-left-animation/5.png",
    "/images/idle-left-animation/6.png",
    "/images/idle-left-animation/7.png",
    "/images/idle-left-animation/8.png",
    "/images/idle-left-animation/9.png",
    "/images/idle-left-animation/10.png",
    "/images/idle-left-animation/11.png",
    "/images/idle-left-animation/12.png",
    "/images/idle-left-animation/13.png",
    "/images/idle-left-animation/14.png",
    "/images/idle-left-animation/15.png",
    "/images/idle-left-animation/16.png",
    "/images/idle-left-animation/17.png"
  ]
  description: "Animation de position statique sur le profil gauche"
  rotation: 1
idle-right-animation:
  type: 2
  path: [
    "/images/idle-right-animation/1.png",
    "/images/idle-right-animation/2.png",
    "/images/idle-right-animation/3.png",
    "/images/idle-right-animation/4.png",
    "/images/idle-right-animation/5.png",
    "/images/idle-right-animation/6.png",
    "/images/idle-right-animation/7.png",
    "/images/idle-right-animation/8.png",
    "/images/idle-right-animation/9.png",
    "/images/idle-right-animation/10.png",
    "/images/idle-right-animation/11.png",
    "/images/idle-right-animation/12.png",
    "/images/idle-right-animation/13.png",
    "/images/idle-right-animation/14.png",
    "/images/idle-right-animation/15.png",
    "/images/idle-right-animation/16.png",
    "/images/idle-right-animation/17.png"
  ]
  description: "Animation de position statique sur le profil droit"
  rotation: 1
front-walk:
  type: 3
  path: [
    "/images/front-walk/1.png",
    "/images/front-walk/2.png",
    "/images/front-walk/3.png",
    "/images/front-walk/4.png",
    "/images/front-walk/5.png",
    "/images/front-walk/6.png",
    "/images/front-walk/7.png",
    "/images/front-walk/8.png",
    "/images/front-walk/9.png",
    "/images/front-walk/10.png",
    "/images/front-walk/11.png",
    "/images/front-walk/12.png",
    "/images/front-walk/13.png",
    "/images/front-walk/14.png",
    "/images/front-walk/15.png",
    "/images/front-walk/16.png",
    "/images/front-walk/17.png"
  ]
  description: "Marche vers le bas"
  rotation: 1
right-walk:
  type: 3
  path: [
    "/images/right-walk/1.png",
    "/images/right-walk/2.png",
    "/images/right-walk/3.png",
    "/images/right-walk/4.png",
    "/images/right-walk/5.png",
    "/images/right-walk/6.png",
    "/images/right-walk/7.png",
    "/images/right-walk/8.png",
    "/images/right-walk/9.png",
    "/images/right-walk/10.png",
    "/images/right-walk/11.png",
    "/images/right-walk/12.png",
    "/images/right-walk/13.png",
    "/images/right-walk/14.png",
    "/images/right-walk/15.png",
    "/images/right-walk/16.png",
    "/images/right-walk/17.png"
  ]
  description: "Marche vers la droite"
  rotation: 1
left-walk:
  type: 3
  path: [
    "/images/left-walk/1.png",
    "/images/left-walk/2.png",
    "/images/left-walk/3.png",
    "/images/left-walk/4.png",
    "/images/left-walk/5.png",
    "/images/left-walk/6.png",
    "/images/left-walk/7.png",
    "/images/left-walk/8.png",
    "/images/left-walk/9.png",
    "/images/left-walk/10.png",
    "/images/left-walk/11.png",
    "/images/left-walk/12.png",
    "/images/left-walk/13.png",
    "/images/left-walk/14.png",
    "/images/left-walk/15.png",
    "/images/left-walk/16.png",
    "/images/left-walk/17.png"
  ]
  description: "Marche vers la gauche"
  rotation: 1
back-walk:
  type: 3
  path: [
    "/images/back-walk/1.png",
    "/images/back-walk/2.png",
    "/images/back-walk/3.png",
    "/images/back-walk/4.png",
    "/images/back-walk/5.png",
    "/images/back-walk/6.png",
    "/images/back-walk/7.png",
    "/images/back-walk/8.png",
    "/images/back-walk/9.png",
    "/images/back-walk/10.png",
    "/images/back-walk/11.png",
    "/images/back-walk/12.png",
    "/images/back-walk/13.png",
    "/images/back-walk/14.png",
    "/images/back-walk/15.png",
    "/images/back-walk/16.png",
    "/images/back-walk/17.png"
  ]
  description: "Marche vers le haut"
  rotation: 1
