1:
  path: "/images/wallstone.png"
  description: "Pierre de mur"
  type: 1
  rotation: 1
2:
  path: "/images/wallstone-fence.png"
  description: "Pierre de clotûre"
  type: 1
  rotation: 1
3:
  path: "/images/wall-breakable.png"
  description: "Mur cassable"
  type: 1
  rotation: 1
4:
  path: "/images/wall-breakable-fence.png"
  description: "Clotûre de mur cassable"
  type: 1
  rotation: 1
5:
  path: "/images/stair.png"
  description: "Escalier de sortie"
  type: 1
  rotation: 1
6:
  path: "/images/small-wallstone.png"
  description: "Petite pierre"
  type: 1
  rotation: 1
7:
  path: "/images/ground-earth.png"
  description: "Herbe de sol"
  type: 1
  rotation: 1
