front-walk:
  path: [
    "/images/front-walk/1.png",
    "/images/front-walk/2.png",
    "/images/front-walk/3.png",
    "/images/front-walk/4.png",
    "/images/front-walk/5.png",
    "/images/front-walk/6.png",
    "/images/front-walk/7.png",
    "/images/front-walk/8.png",
    "/images/front-walk/9.png",
    "/images/front-walk/10.png",
    "/images/front-walk/11.png",
    "/images/front-walk/12.png",
    "/images/front-walk/13.png",
    "/images/front-walk/14.png"
  ]
  description: "Marche vers le bas"
  type: 2
  rotation: 1
right-walk:
  path: [
    "/images/right-walk/1.png",
    "/images/right-walk/2.png",
    "/images/right-walk/3.png",
    "/images/right-walk/4.png",
    "/images/right-walk/5.png",
    "/images/right-walk/6.png",
    "/images/right-walk/7.png",
    "/images/right-walk/8.png",
    "/images/right-walk/9.png",
    "/images/right-walk/10.png",
    "/images/right-walk/11.png",
    "/images/right-walk/12.png",
    "/images/right-walk/13.png",
    "/images/right-walk/14.png"
  ]
  description: "Marche vers la droite"
  type: 2
  rotation: 1
left-walk:
  path: [
    "/images/left-walk/1.png",
    "/images/left-walk/2.png",
    "/images/left-walk/3.png",
    "/images/left-walk/4.png",
    "/images/left-walk/5.png",
    "/images/left-walk/6.png",
    "/images/left-walk/7.png",
    "/images/left-walk/8.png",
    "/images/left-walk/9.png",
    "/images/left-walk/10.png",
    "/images/left-walk/11.png",
    "/images/left-walk/12.png",
    "/images/left-walk/13.png",
    "/images/left-walk/14.png"
  ]
  description: "Marche vers la gauche"
  type: 2
  rotation: 1
back-walk:
  path: [
    "/images/back-walk/1.png",
    "/images/back-walk/2.png",
    "/images/back-walk/3.png",
    "/images/back-walk/4.png",
    "/images/back-walk/5.png",
    "/images/back-walk/6.png",
    "/images/back-walk/7.png",
    "/images/back-walk/8.png",
    "/images/back-walk/9.png",
    "/images/back-walk/10.png",
    "/images/back-walk/11.png",
    "/images/back-walk/12.png",
    "/images/back-walk/13.png",
    "/images/back-walk/14.png"
  ]
  description: "Marche vers le haut"
  type: 2
  rotation: 1
